package testutils

import (
	"context"
	"fmt"
	"math/rand"
	"strings"
	"testing"

	"github.com/google/uuid"
	"github.com/stretchr/testify/require"
	"github.com/ubuntu/gowsl"
)

const (
	testDistroPrefix = "testDistro_UP4W"
)

// NonRegisteredDistro generates a random distroName and GUID but does not register them.
func NonRegisteredDistro(t *testing.T) (distroName string, GUID string) {
	t.Helper()

	distroName = RandomDistroName(t)

	guid, err := uuid.NewRandom()
	require.NoError(t, err, "Setup: could not generate a GUID for the non-registered distro")

	GUID = fmt.Sprintf("{%s}", guid.String())
	return distroName, GUID
}

// RandomDistroName generates a distroName that is not registered.
func RandomDistroName(t *testing.T) (name string) {
	t.Helper()

	testFullNormalized := normalizeName(t, strings.ReplaceAll(t.Name(), "/", "--"))

	//nolint:gosec // No need to be cryptographically secure
	return fmt.Sprintf("%s_%s_%d", testDistroPrefix, testFullNormalized, rand.Uint64())
}

// DistroState returns the state of the distro as specified by wsl.exe. Possible states:
// - Installing
// - Running
// - Stopped
// - Unregistered.
func DistroState(t *testing.T, ctx context.Context, distroName string) string {
	t.Helper()

	d := gowsl.NewDistro(ctx, distroName)
	s, err := d.State()
	require.NoError(t, err) // Error message is explanatory enough
	return s.String()
}

// requireIsTestDistro requires a distroName to match those generated by the testutils.
// It is intended to protect other distros in the machine.
func requireIsTestDistro(t *testing.T, distroName string) {
	t.Helper()

	if !strings.HasPrefix(distroName, testDistroPrefix) {
		require.Fail(t, "testutils can only be used with test distros", "Requested distro: %s", distroName)
	}
}
