version: 2
updates:
  # General Go dependency updates for all Go modules in the repository.
  - package-ecosystem: "gomod"
    directories:
      - "/agentapi"
      - "/common"
      - "/contractsapi"
      - "/end-to-end"
      - "/generate"
      - "/mocks"
      - "/storeapi/go-wrapper/microsoftstore"
      - "/tools"
      - "/windows-agent/"
      - "/wsl-pro-service"
    commit-message:
      prefix: "deps(go): "
    schedule:
      interval: "weekly"
      day: "thursday"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    commit-message:
      prefix: "deps(gh-actions): "
    schedule:
      interval: "weekly"
      day: "thursday"

  # So we update grpc and protobuf packages exclusively.
  - package-ecosystem: "pub"
    directory: "/agentapi/dart"
    commit-message:
      prefix: "deps(agentapi): "
    schedule:
      interval: "weekly"
      day: "thursday"

  # Other Dart packages update more often.
  - package-ecosystem: "pub"
    directories:
      - "/gui/packages/p4w_ms_store"
      - "/gui/packages/ubuntupro"
    commit-message:
      prefix: "deps(gui): "
    schedule:
      interval: "weekly"
      day: "thursday"
