// Mocks generated by Mockito 5.4.2 from annotations
// in ubuntupro/test/pages/subscription_status/subscribe_now_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:ubuntupro/core/agent_api_client.dart' as _i2;
import 'package:ubuntupro/core/pro_token.dart' as _i5;
import 'package:ubuntupro/pages/subscription_status/subscription_status_model.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAgentApiClient_0 extends _i1.SmartFake
    implements _i2.AgentApiClient {
  _FakeAgentApiClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SubscribeNowModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscribeNowModel extends _i1.Mock implements _i3.SubscribeNowModel {
  MockSubscribeNowModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AgentApiClient get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeAgentApiClient_0(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.AgentApiClient);
  @override
  _i4.Future<void> applyProToken(_i5.ProToken? token) => (super.noSuchMethod(
        Invocation.method(
          #applyProToken,
          [token],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  void launchProWebPage() => super.noSuchMethod(
        Invocation.method(
          #launchProWebPage,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Future<void> purchaseSubscription() => (super.noSuchMethod(
        Invocation.method(
          #purchaseSubscription,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
