name: Flutter Quality Checks
description: Setup Flutter and run the quality checks.

inputs:
  flutter-version:
    required: true
    description: "The Flutter SDK version to use."
  package-dir:
    required: true
    description: "The root directory of the package to lint."
  run-build-runner:
    default: 'false'
    description: "Whether we must run build-runner for this package."    

runs:
  using: "composite"
  steps:
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '${{ inputs.flutter-version }}'
    - name: Format
      shell: bash
      working-directory: '${{ inputs.package-dir }}'
      run: |
        find . -name '*.dart' \
          ! -name '*.g.dart' \
          ! -name '*.freezed.dart' \
          ! -path '*/l10n/*' \
          ! -path "*/.*/*" \
          | xargs flutter format --set-exit-if-changed
    - name: Dart Codegen
      if: ${{ inputs.run-build-runner == 'true' }}
      shell: bash
      working-directory: '${{ inputs.package-dir }}'
      run: flutter pub get && flutter pub run build_runner build --delete-conflicting-outputs
    - name: Analyze
      shell: bash
      working-directory: '${{ inputs.package-dir }}'
      run: flutter analyze 
    - name: Test
      shell: bash
      working-directory: '${{ inputs.package-dir }}'
      run: flutter test 
