//go:build windows && realwsl && !gowslmock

// Real-WSL end-to-end tests: against a live distro, verify the EA stamp
// actually projects root ownership inside WSL and that a sub-custodian cannot
// reach a sibling's sub-tree. These are the only tests exercising the
// production path end to end.

package securefiles_test

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/canonical/ubuntu-pro-for-wsl/common/wsltestutils"
	"github.com/canonical/ubuntu-pro-for-wsl/windows-agent/internal/securefiles"
	"github.com/stretchr/testify/require"
)

func TestProjectionRootOwnedInDistro(t *testing.T) {
	distroName, _ := requireRealWsl2Instance(t)

	dir := t.TempDir()
	c, err := securefiles.Open(dir)
	require.NoError(t, err)
	defer c.Close()

	// The sealed directory is a nested custodian root, mirroring how production
	// creates .cloud-init and certificates: Subdir stamps the directory itself.
	sealed, err := c.Subdir("sealed_dir")
	require.NoError(t, err)
	defer sealed.Close()

	err = sealed.WriteFile("client.key", []byte("secret_client_key"))
	require.NoError(t, err)

	ctx, cancel := context.WithTimeout(context.Background(), 1*time.Minute)
	defer cancel()

	wslPath := "/mnt/" + strings.ToLower(dir[0:1]) + "/" + filepath.ToSlash(dir[3:])
	sealedDirWsl := wslPath + "/sealed_dir"
	clientKeyWsl := sealedDirWsl + "/client.key"

	out, err := exec.CommandContext(ctx, "wsl.exe", "-d", distroName, "-u", "root", "--", "stat", "-c", "%u:%g:%a", sealedDirWsl).CombinedOutput() //nolint:gosec // Distro name is generated by the test and WSL paths are derived from t.TempDir().
	require.NoError(t, err, "stat sealed_dir output: %s", out)
	dirStat := strings.TrimSpace(string(out))
	require.Equal(t, "0:0:700", dirStat)

	out, err = exec.CommandContext(ctx, "wsl.exe", "-d", distroName, "-u", "root", "--", "stat", "-c", "%u:%g:%a", clientKeyWsl).CombinedOutput() //nolint:gosec // Distro name is generated by the test and WSL paths are derived from t.TempDir().
	require.NoError(t, err, "stat client.key output: %s", out)
	keyStat := strings.TrimSpace(string(out))
	require.Equal(t, "0:0:600", keyStat)

	cmd := exec.CommandContext(ctx, "wsl.exe", "-d", distroName, "-u", "nobody", "--", "cat", clientKeyWsl) //nolint:gosec // Distro name is generated by the test and WSL paths are derived from t.TempDir().
	out, err = cmd.CombinedOutput()
	require.Error(t, err, "Expected permission denied when unprivileged process reads key: output: %s", out)
}

// TestSubScopedCustodianCannotReachSibling proves the sub-scoping property the
// cloud-init writer relies on: a custodian scoped to one sub-tree cannot name,
// let alone write, a node in a sibling sub-tree, so per-distro data can never
// reach the certificates.
func TestSubScopedCustodianCannotReachSibling(t *testing.T) {
	t.Parallel()

	publicDir := t.TempDir()

	// Seed a sibling file that a sub-scoped custodian must not be able to touch.
	siblingPath := filepath.Join(publicDir, "certificates", "sibling.key")
	require.NoError(t, os.MkdirAll(filepath.Dir(siblingPath), 0700))
	require.NoError(t, os.WriteFile(siblingPath, []byte("sibling"), 0600))

	parent, err := securefiles.Open(publicDir)
	require.NoError(t, err)
	defer parent.Close()

	custodian, err := parent.Subdir(".cloud-init")
	require.NoError(t, err)
	defer custodian.Close()

	// Attempting to name a file so the path escapes the sub-tree must fail.
	err = custodian.WriteFile("../certificates/sibling", []byte("data"))
	require.ErrorIs(t, err, securefiles.ErrPathEscapes)

	// The sibling content must be untouched.
	got, err := os.ReadFile(siblingPath)
	require.NoError(t, err)
	require.Equal(t, "sibling", string(got))
}

func requireRealWsl2Instance(t *testing.T) (string, string) {
	t.Helper()

	rootFsPath := os.Getenv("UP4W_TEST_ROOTFS")
	require.NotEmpty(t, rootFsPath, "Setup: projection test requires real distro rootfs available (set UP4W_TEST_ROOTFS)")

	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()

	distroName := wsltestutils.RandomDistroName(t)
	guid := wsltestutils.PowershellInstallDistro(t, ctx, distroName, rootFsPath)

	return distroName, guid
}
