name: Flutter Integration Tests
description: Setup Flutter and run the integration tests.

inputs:
  flutter-version:
    required: true
    description: "The Flutter SDK version to use."
  go-version-file:
    required: true
    description: "The file from which we derive the required Go version."
  package-dir:
    required: true
    description: "The root directory of the package to lint."

runs:
  using: "composite"
  steps:
    - uses: microsoft/setup-msbuild@v3
      if: runner.os == 'Windows'
    # Go is needed to build the agent for integration testing.
    - uses: actions/setup-go@v6
      with:
        cache-dependency-path: "${{ inputs.go-version-file }}"
        go-version-file: "${{ inputs.go-version-file }}"
    - uses: subosito/flutter-action@v2
      with:
        cache: true
        channel: "stable"
        flutter-version: "${{ inputs.flutter-version }}"
    - name: Integration Test
      shell: bash
      working-directory: '${{ inputs.package-dir }}'
      run: |
        if [ ! -d integration_test ]; then
          echo "::warning::No integration tests found, skipping."
          exit 0
        fi

        if [ $(uname) = 'Linux' ]; then
          xvfb-run -a -s '-screen 0 1024x768x24 +extension GLX' \
            flutter test --coverage integration_test/
        else
            flutter test --coverage integration_test/
        fi
        dart pub global activate cobertura
        # Default input is coverage/lcov.info and output is coverage/cobertura.xml
        dart pub global run cobertura convert
    - name: Upload coverage artifacts
      uses: actions/upload-artifact@v7
      with:
        name: coverage-${{ matrix.package }}-${{ matrix.os }}-integration
        path: ${{ inputs.package-dir }}/coverage/*
    - name: Cleanup
      shell: bash
      working-directory: "${{ inputs.package-dir }}"
      run: |
        rm -rf ./coverage
