@startuml
set separator none
title UP4W - Deployment - UbuntuProForWSL

top to bottom direction

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam rectangle<<UbuntuProForWSL.YourcomputerWindowshost.WSLVM.UbuntuWSLinstancedistro.LandscapeClient_1>> {
  BackgroundColor #999999
  FontColor #ffffff
  BorderColor #6b6b6b
  roundCorner 20
  shadowing false
}
skinparam rectangle<<UbuntuProForWSL.Someoneelsescomputer.LandscapeServer_1>> {
  BackgroundColor #999999
  FontColor #ffffff
  BorderColor #6b6b6b
  roundCorner 20
  shadowing false
}
skinparam rectangle<<UbuntuProForWSL.Someoneelsescomputer>> {
  BackgroundColor #ffffff
  FontColor #000000
  BorderColor #888888
  roundCorner 20
  shadowing false
}
skinparam rectangle<<UbuntuProForWSL.YourcomputerWindowshost.UP4WWindowsAgent_1>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2e6295
  roundCorner 20
  shadowing false
}
skinparam rectangle<<UbuntuProForWSL.YourcomputerWindowshost.UP4WWindowsGUI_1>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2e6295
  roundCorner 20
  shadowing false
}
skinparam rectangle<<UbuntuProForWSL.YourcomputerWindowshost.WSLVM.UbuntuWSLinstancedistro.UbuntuProClient_1>> {
  BackgroundColor #999999
  FontColor #ffffff
  BorderColor #6b6b6b
  roundCorner 20
  shadowing false
}
skinparam rectangle<<UbuntuProForWSL.YourcomputerWindowshost.WSLVM.UbuntuWSLinstancedistro>> {
  BackgroundColor #ffffff
  FontColor #000000
  BorderColor #888888
  roundCorner 20
  shadowing false
}
skinparam rectangle<<UbuntuProForWSL.YourcomputerWindowshost.WSLVM>> {
  BackgroundColor #ffffff
  FontColor #000000
  BorderColor #888888
  roundCorner 20
  shadowing false
}
skinparam rectangle<<UbuntuProForWSL.YourcomputerWindowshost.WSLVM.UbuntuWSLinstancedistro.WSLProService_1>> {
  BackgroundColor #1168bd
  FontColor #ffffff
  BorderColor #0b4884
  roundCorner 20
  shadowing false
}
skinparam rectangle<<UbuntuProForWSL.YourcomputerWindowshost.Windowsregistry_1>> {
  BackgroundColor #999999
  FontColor #ffffff
  BorderColor #6b6b6b
  roundCorner 20
  shadowing false
}
skinparam rectangle<<UbuntuProForWSL.YourcomputerWindowshost>> {
  BackgroundColor #ffffff
  FontColor #000000
  BorderColor #888888
  roundCorner 20
  shadowing false
}

rectangle "Your computer = Windows host\n<size:10>[Deployment Node: Windows]</size>" <<UbuntuProForWSL.YourcomputerWindowshost>> as UbuntuProForWSL.YourcomputerWindowshost {
  rectangle "UP4W appx" <<group1>> {
    skinparam RectangleBorderColor<<group1>> #cccccc
    skinparam RectangleFontColor<<group1>> #cccccc
    skinparam RectangleBorderStyle<<group1>> dashed

    rectangle "==UP4W Windows GUI" <<UbuntuProForWSL.YourcomputerWindowshost.UP4WWindowsGUI_1>> as UbuntuProForWSL.YourcomputerWindowshost.UP4WWindowsGUI_1
    rectangle "==UP4W Windows Agent" <<UbuntuProForWSL.YourcomputerWindowshost.UP4WWindowsAgent_1>> as UbuntuProForWSL.YourcomputerWindowshost.UP4WWindowsAgent_1
  }

  rectangle "==Windows registry" <<UbuntuProForWSL.YourcomputerWindowshost.Windowsregistry_1>> as UbuntuProForWSL.YourcomputerWindowshost.Windowsregistry_1
  rectangle "WSL (VM)\n<size:10>[Deployment Node]</size>" <<UbuntuProForWSL.YourcomputerWindowshost.WSLVM>> as UbuntuProForWSL.YourcomputerWindowshost.WSLVM {
    rectangle "Ubuntu WSL instance (distro)\n<size:10>[Deployment Node: Ubuntu (Preview)]</size>" <<UbuntuProForWSL.YourcomputerWindowshost.WSLVM.UbuntuWSLinstancedistro>> as UbuntuProForWSL.YourcomputerWindowshost.WSLVM.UbuntuWSLinstancedistro {
      rectangle "==WSL Pro Service" <<UbuntuProForWSL.YourcomputerWindowshost.WSLVM.UbuntuWSLinstancedistro.WSLProService_1>> as UbuntuProForWSL.YourcomputerWindowshost.WSLVM.UbuntuWSLinstancedistro.WSLProService_1
      rectangle "==Ubuntu Pro Client" <<UbuntuProForWSL.YourcomputerWindowshost.WSLVM.UbuntuWSLinstancedistro.UbuntuProClient_1>> as UbuntuProForWSL.YourcomputerWindowshost.WSLVM.UbuntuWSLinstancedistro.UbuntuProClient_1
      rectangle "==Landscape Client" <<UbuntuProForWSL.YourcomputerWindowshost.WSLVM.UbuntuWSLinstancedistro.LandscapeClient_1>> as UbuntuProForWSL.YourcomputerWindowshost.WSLVM.UbuntuWSLinstancedistro.LandscapeClient_1
    }

  }

}

rectangle "Someone else's computer\n<size:10>[Deployment Node]</size>" <<UbuntuProForWSL.Someoneelsescomputer>> as UbuntuProForWSL.Someoneelsescomputer {
  rectangle "==Landscape Server" <<UbuntuProForWSL.Someoneelsescomputer.LandscapeServer_1>> as UbuntuProForWSL.Someoneelsescomputer.LandscapeServer_1
}

UbuntuProForWSL.YourcomputerWindowshost.UP4WWindowsGUI_1 .[#707070,thickness=2].> UbuntuProForWSL.YourcomputerWindowshost.UP4WWindowsAgent_1 : "<color:#707070>Writes configuration to"
UbuntuProForWSL.YourcomputerWindowshost.UP4WWindowsAgent_1 .[#707070,thickness=2].> UbuntuProForWSL.YourcomputerWindowshost.Windowsregistry_1 : "<color:#707070>Reads configuration from"
UbuntuProForWSL.YourcomputerWindowshost.UP4WWindowsAgent_1 .[#707070,thickness=2].> UbuntuProForWSL.YourcomputerWindowshost.WSLVM.UbuntuWSLinstancedistro.WSLProService_1 : "<color:#707070>Sends configuration to"
UbuntuProForWSL.YourcomputerWindowshost.WSLVM.UbuntuWSLinstancedistro.WSLProService_1 .[#707070,thickness=2].> UbuntuProForWSL.YourcomputerWindowshost.WSLVM.UbuntuWSLinstancedistro.UbuntuProClient_1 : "<color:#707070>Configures"
UbuntuProForWSL.YourcomputerWindowshost.WSLVM.UbuntuWSLinstancedistro.WSLProService_1 .[#707070,thickness=2].> UbuntuProForWSL.YourcomputerWindowshost.WSLVM.UbuntuWSLinstancedistro.LandscapeClient_1 : "<color:#707070>Configures"
UbuntuProForWSL.Someoneelsescomputer.LandscapeServer_1 .[#707070,thickness=2].> UbuntuProForWSL.YourcomputerWindowshost.WSLVM.UbuntuWSLinstancedistro.LandscapeClient_1 : "<color:#707070>Reads from and sends instructions to"
UbuntuProForWSL.Someoneelsescomputer.LandscapeServer_1 .[#707070,thickness=2].> UbuntuProForWSL.YourcomputerWindowshost.UP4WWindowsAgent_1 : "<color:#707070>Reads from and sends instructions to"
@enduml