$ErrorActionPreference = 'Stop'

$packageName = $env:ChocolateyPackageName
$packageVersion = $env:ChocolateyPackageVersion
$toolsDir = "$(Split-Path -parent $MyInvocation.MyCommand.Definition)"
$assetFile = Join-Path $toolsDir "asset.json"

[int]$majorVersion = [Environment]::OSVersion.Version.Major
if ($majorVersion -lt 10) {
    throw "This package requires Windows 10 or later."
}

[int]$osBuild = [Environment]::OSVersion.Version.Build
if ($osBuild -lt 19041) {
    throw "This package requires at least Windows 10 version 2004/OS build 19041.x. Current build: $osBuild"
}


# The asset.json file is generated by CI at release time.
# Expected structure:
# {
#   "version": "<MSIX package version>",
#   "tag": "<release tag>",
#   "name": "<asset file name>",
#   "download_url": "<https URL to the .msixbundle asset>",
#   "checksum": {
#     "value": "<checksum string>",
#     "type": "<checksum algorithm, e.g. sha256>"
#   }
# }
$asset = Get-Content -Raw -Path "$assetFile" | ConvertFrom-Json
$url = $asset.download_url
$checksum = $asset.checksum.value
$type = $asset.checksum.type

$msixBundleFileName = $asset.name
$downloadPath = Join-Path $toolsDir $msixBundleFileName

Write-Verbose "Downloading $msixBundleFileName from $url"
# Use the Chocolatey helper function to download the file securely.
Get-ChocolateyWebFile	        `
    -PackageName $packageName   `
    -FileFullPath $downloadPath `
    -Url $url			`
    -Checksum $checksum		`
    -ChecksumType $type

# MSIX installations must use native PowerShell cmdlets (Add-AppxProvisionedPackage).
# This command installs the package system-wide, making it available for all users (provisioning).
Write-Host "Installing MSIX Bundle via Add-AppxProvisionedPackage for machine-wide availability..."

try {
    # Use -Online to target the running operating system image.
    # Use -SkipLicense for packages without a required license file.
    Add-AppxProvisionedPackage -Online -PackagePath $downloadPath -SkipLicense -ErrorAction Stop

    Write-Host "$packageName installed successfully."
}
catch {
    Write-Error "Failed to install MSIX Bundle: $($_.Exception.Message)"
    # Re-throw the error to fail the Chocolatey package installation gracefully.
    throw
}

Write-Host "Installation of ${env:ChocolateyPackageName} complete."
if (Test-Path $downloadPath) {
    Remove-Item $downloadPath -Force
    Write-Host "Cleaned up downloaded file: $msixBundleFileName"
}
