name: Update translations
on:
  push:
    branches:
      - main
      - translate-go # TODO: This line is only for testing, remove before merging
    paths-ignore:
      - po/*
      - README.md
      - wsl-pro-service/debian/control

jobs:
  update-po:
    name: Update po files
    runs-on: ubuntu-latest
    env:
      modified: false
    steps:
      - name: Install dependencies
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt update
          sudo DEBIAN_FRONTEND=noninteractive apt install -y gettext
      - uses: actions/checkout@v3
        name: Check out repo
        # with:
        #   ref: main
        # TODO: These lines are commented out only for testing, enable before merging
      - uses: actions/setup-go@v4
        with:
          go-version-file: common/go.mod
      - name: Check po files
        id: checkpo
        run: |
          set -eu

          hasModif="false"

          go generate common/i18n/i18n.go

          # Exclude line diffs only
          MODIFIED=$(git difftool -y -x "diff -Nup -I '^#: '" po/)
          if [ -n "$MODIFIED" ]; then
            hasModif="true"
          fi
          echo "modified=${hasModif}" >> $GITHUB_ENV
      - name: Create Pull Request
        if: ${{ env.modified == 'true' }}
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Auto update po files
          title: Auto update po files
          labels: po, automated pr
          body: "[Auto-generated pull request](https://github.com/canonical/ubuntu-pro-for-windows/actions/workflows/auto-updates.yaml) by GitHub Action"
          branch: auto-update/po
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Push branch
        if: ${{ env.modified == 'true' }}
        run: |
          git push origin auto-update/po:main
