name: Documentation auto-update
on:
  push:
    branches:
      - main
      - documentation # TODO: Test entry, remove before merging
    paths-ignore:
      - po/*
      - README.md
      - '**/debian/control'

env:
  modified: false
  subprojects: windows-agent wsl-pro-service
  apt_dependencies: >-
    git

  # ca-certificates curl dconf-cli gcc gettext git libnss-wrapper libsmbclient-dev
  # libwbclient-dev pkg-config protobuf-compiler python3-coverage samba sudo

jobs:
  update-readme-cli-ref:
    name: Update readme and CLI ref files
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt update
          sudo DEBIAN_FRONTEND=noninteractive apt install -y ${{ env.apt_dependencies }}
      - name: Set up git
        uses: canonical/ubuntu-pro-for-windows/.github/actions/setup-git@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
        name: Check out repository
        # with:
        #   ref: main
        # TODO: Test ##, uncomment before merging 
      - uses: actions/setup-go@v4
        name: Set up Go
        with:
          go-version-file: go.work
      - name: Check README file
        run: |
          set -eu

          for subproject in ${{ env.subprojects }} ; do
            cd "${{ github.workspace }}/${subproject}/cmd/"
            go run generate_completion_documentation.go update-readme
            go run generate_completion_documentation.go update-doc-cli-ref
          done

          hasModif="false"
          MODIFIED=$(git status --porcelain --untracked-files=no)
          if [ -n "$MODIFIED" ]; then
            hasModif="true"
          fi
          echo "modified=${hasModif}" >> $GITHUB_ENV
      - uses: peter-evans/create-pull-request@v4
        name: Create Pull Request
        if: ${{ env.modified == 'true' }}
        with:
          commit-message: Auto update readme files
          title: Auto update readme files
          labels: readme, automated pr
          body: "[Auto-generated pull request](https://github.com/canonical/ubuntu-pro-for-windows/actions/workflows/auto-updates.yaml) by GitHub Action"
          branch: auto-update-readme-cli-ref
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Push branch
        if: ${{ env.modified == 'true' }}
        run: |
          git push origin auto-update-readme-cli-ref:main
