name: Publish MSIX app to the Microsoft Store
concurrency: publish-msix-${{ github.event_name == 'pull_request' && github.ref || 'production' }}
on:
  workflow_dispatch:
  push:
    tags:
      - '**'
      - '!*.post[0-9]+' # Reserved for documentation-only releases.
      - '!wsl-pro-service/**'
  pull_request:
    paths:
      - '.github/workflows/publish-msix.yaml'
jobs:
  version:
    name: Compute version
    runs-on: ubuntu-latest
    outputs:
      numeric-version: ${{ steps.version.outputs.numeric_version }}
      full-version: ${{ steps.version.outputs.full_version }}
      tag: ${{ steps.version.outputs.tag }}
      release-type: ${{ steps.version.outputs.release_type }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
        with:
          fetch-tags: true
          fetch-depth: 0
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.work
          cache-dependency-path: go.work
      - name: Compute version
        id: version
        run: |
          versionInfo=$(go run ./tools/build/compute_version.go --json)
          echo "numeric_version=$(jq -r '.numeric_version' <<< "$versionInfo").0" >> "$GITHUB_OUTPUT"
          echo "full_version=$(jq -r '.full_version' <<< "$versionInfo")"         >> "$GITHUB_OUTPUT"
          echo "tag=$(jq -r '.tag' <<< "$versionInfo")"                           >> "$GITHUB_OUTPUT"
          echo "release_type=$(jq -r '.release_type' <<< "$versionInfo")"         >> "$GITHUB_OUTPUT"

  build:
    name: Build (${{ matrix.runner }})
    needs: version
    permissions:
      contents: read
    strategy:
      matrix:
        runner: [windows-2025, windows-11-vs2026-arm]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
        with:
          fetch-tags: true
          fetch-depth: 0
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.work
          cache-dependency-path: go.work
      - name: Read flutter version
        id: flutter-version
        uses: ./.github/actions/read-file
        with:
          path: tools/flutter-version
      - uses: CarlosNihelton/flutter-action@53984264025d6f0cda85838542ad2d440351ceb7
        with:
          cache: true
          channel: stable
          flutter-version: ${{ steps.flutter-version.outputs.contents }}
          pub-cache: true
      - uses: microsoft/setup-WinAppCli@2e1c15e9fe58b43697420e71d3aac9e6cd956273 # v0.1
      - name: Build components
        shell: powershell
        run: |
          $platform = if ($env:PROCESSOR_ARCHITECTURE -eq 'ARM64') { 'arm64' } else { 'x64' }
          $compileArgs = @{
            Config = 'Release'
            Platform = $platform
            Mode = 'production'
            FullVersion = '${{ needs.version.outputs.full-version }}'
            Version = '${{ needs.version.outputs.numeric-version }}'
            Tag = '${{ needs.version.outputs.Tag }}'
          }
          .\build.ps1 Compile @compileArgs
          if ($LASTEXITCODE -ne 0) { throw "build.ps1 Compile failed" }
      - name: Upload dist folder
        uses: actions/upload-artifact@v7
        with:
          name: dist-${{ matrix.runner }}
          path: dist/
          if-no-files-found: error

  publish-msix:
    name: Publish MSIX app to the Microsoft Store
    needs: [version, build]
    permissions:
      contents: write
    runs-on: windows-2025
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
        with:
          fetch-tags: true
          fetch-depth: 0
      - name: Download dist artifacts
        uses: actions/download-artifact@v8
        with:
          # No name to download them all, merge-multiple to put their contents under the same `dist` directory.
          # End result should then be: [dist/arm64/ dist/x64].
          path: dist
          merge-multiple: true
      - name: Install winappCLI
        uses: microsoft/setup-WinAppCli@2e1c15e9fe58b43697420e71d3aac9e6cd956273 # v0.1
      - name: Pack MSIX bundle
        id: bundle
        # The Pack action with a password protected PFX certificate requires PowerShell 7.
        shell: pwsh
        run: |
          # Decode certificate
          New-Item -ItemType directory -Path certificate
          Set-Content -Path certificate\certificate.txt -Value '${{ secrets.CERTIFICATE }}'
          certutil -decode certificate\certificate.txt certificate\certificate.pfx
          $certPass = ConvertTo-SecureString '${{ secrets.CERTIFICATE_PASSWORD }}' -AsPlainText -Force

          # Outputs as expected by the App Installer file.
          .\build.ps1 Pack -Manifest "$PWD/dist/Package.appxmanifest" -InputFolders "$PWD/dist/x64","$PWD/dist/arm64" `
              -Output UbuntuProForWSL.msixbundle -Cert "$PWD/certificate/certificate.pfx" -CertPass $certPass

          if ($LASTEXITCODE -ne 0) { throw "build.ps1 Pack failed" }
          
          # Propagate outputs
          $msixFiles = Get-ChildItem -Path . -Filter '*.msixbundle'
          # Both architectures should have app installer files with the exact same contents.
          $appinstallerFile = "$PWD/dist/x64/UbuntuProForWSL.appinstaller"
          "bundle-path=$($msixFiles[0].FullName)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
          "appinstaller-path=$appinstallerFile" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
      - name: Upload MSIX bundle (dry-run)
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v7
        with:
          name: msix-bundle
          path: |
            ${{ steps.bundle.outputs.bundle-path }}
            ${{ steps.bundle.outputs.appinstaller-path }}
          if-no-files-found: error
      - name: Install Store Broker
        if: github.event_name != 'pull_request'
        shell: powershell
        run: |
          Install-Module -Name StoreBroker -AcceptLicense -Force -Scope CurrentUser -Verbose
      - name: Submit to Microsoft Store
        if: github.event_name != 'pull_request'
        shell: powershell
        env:
          pre_release: ${{ needs.version.outputs.release-type }}
        run: |
          New-Item -ItemType directory -Path store -Force

          # Authenticate against the store
          $pass = ConvertTo-SecureString -String '${{ secrets.PRO_APP_PUBLICATION_APPKEY }}' -AsPlainText -Force
          $cred = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList ${{ secrets.AZUREAD_APPID }},$pass
          Set-StoreBrokerAuthentication -TenantId '${{ secrets.AZUREAD_TENANTID }}' -Credential $cred

          # Set store app ID for AppID
          $appid = "9PD1WZNBDXKZ"

          # Prepare and submit to the Store
          $sub = ""
          $url = ""
          New-SubmissionPackage -ConfigPath .\msix\SBConfig.json -Verbose
          $subFileStem="out\appstore-submission"
          Get-Content "$subFileStem.json"
          if ($env:pre_release -eq "pre-release") {
            # The existing package flight for beta testers.
            $flightId="876dc297-0b4d-4a74-94ef-720279050fc4"
            Write-Output "Starting a new submission under package flight $flightId from:"
            Get-ChildItem ./
            $sub, $url = Update-ApplicationFlightSubmission -AppId $appid -FlightId $flightId -SubmissionDataPath "$subFileStem.json" -PackagePath "$subFileStem.zip" -Force -AutoCommit -ReplacePackages -Verbose
          } else {
            $sub, $url = Update-ApplicationSubmission -AppId $appid -SubmissionDataPath "$subFileStem.json" -PackagePath "$subFileStem.zip" -Force -ReplacePackages -AutoCommit -Verbose
          }
          Write-Output "If needed the package built by this run can be downloaded from:"
          Write-Output $url
          Write-Output "Access the submission via the link below:"
          Write-Output "https://partner.microsoft.com/en-us/dashboard/products/$appid/submissions/$sub/"
      - name: Create the GH Release
        if: github.event_name != 'pull_request'
        shell: powershell
        id: create-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ needs.version.outputs.numeric-version }}
          pre_release: ${{ needs.version.outputs.release-type }}
          tag: ${{ github.ref_name }}
        # Intentionally not copying the msixbundle, as it is already uploaded to the store
        # We want the msix bundle signed by the store instead, reason why we don't mark this as 'latest'
        # and draft, so it doesn't appear as a published release.
        run: |
          $appinstallerFile="${{ steps.bundle.outputs.appinstaller-path }}"
          if ($env:pre_release -eq "pre-release") {
            Write-output "Creating a new pre-release draft"
            gh release create "${env:tag}" --draft --prerelease --latest=false --generate-notes --title "${env:version}" --verify-tag -- "${appinstallerFile}"
          } else {
            gh release create "${env:tag}" --draft --latest --title "${env:version}" --generate-notes --verify-tag -- "${appinstallerFile}"
          }
          Write-Output "This is a draft release. Once the submission is completed in MS Partner Center, the MSIX package must be downloaded and included as a release asset."
      - name: Check out the repository wiki
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v7
        with:
          repository: canonical/ubuntu-pro-for-wsl.wiki
          path: wiki
      - name: Store the App Installer File for the pre-release audience
        if: github.event_name != 'pull_request'
        shell: powershell
        working-directory: './wiki'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # The appinstaller file output is an absolute path.
        run: |
          $folder = ".\pre-release\"
          New-Item -Path "$folder" -ItemType Directory -Force
          Copy-Item "${{ steps.bundle.outputs.appinstaller-path }}" "$folder"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "$folder"
          git commit -m "Auto-update pre-release assets"
          git push origin master
